[package]
name = "codeql-extractor-ruby"
description = "CodeQL Ruby extractor"
version = "0.1.0"
authors = ["GitHub"]
edition = "2021"

[dependencies]
tree-sitter = ">= 0.23.0"
tree-sitter-embedded-template = "0.23.2"
tree-sitter-ruby = "0.23.1"
clap = { version = "4.2", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3.3", features = ["env-filter"] }
rayon = "1.5.0"
regex = "1.7.1"
encoding = "0.2"
lazy_static = "1.4.0"

codeql-extractor = { path = "../../shared/tree-sitter-extractor" }
